name: CI

on: push

jobs:
  rust:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal -c clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --all-targets

      - run: cargo test --all-targets

      - run: cargo clippy --all-targets -- -D warnings

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install nightly --profile minimal -c rustfmt

      - run: cargo +nightly fmt -- --check
